name: wk1
on:
  pull_request:
    branches: [main]
    
env:
  AZURE_WEBAPP_NAME: my-web-app-2025
  RESOURCE_GROUP: my-web-app-2025_group
jobs:
  complete-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: |
        dotnet publish ./az2006webapp.csproj -c Release -o ./publish
        cd ./publish && zip -r ../app.zip .
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/cli@v2
      with:
        inlineScript: az webapp deployment source config-zip --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --src app.zip --slot staging
    - uses: azure/load-testing@v1
      with:
        loadTestConfigFile: 'config.yml'
        loadTestResource: 'test1.jmx'
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        env: |
          HTTPSample.domain=https://${{ env.AZURE_WEBAPP_NAME }}-staging.azurewebsites.net
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: loadTestResults
        path: loadTest/results.zip

