name: wk1
on:
  pull_request:
    branches: [main]
env:
  AZURE_WEBAPP_NAME: my-web-app-2025
  RESOURCE_GROUP: my-web-app-2025_group

jobs:
  complete-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: |
          dotnet publish ./az2006webapp.csproj -c Release -o ./publish
          cd ./publish && zip -r ../app.zip .
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/cli@v2
        with:
          inlineScript: az webapp deploy --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --src-path app.zip --slot staging
      - name: Install Load Testing Extension
        run: az extension add --name load --yes
      - run: az load-test run --resource-group ${{ env.RESOURCE_GROUP }} --load-test-resource your-load-testing-resource --test-id ebd72e5b-7599-4d82-bfaa-c86dac638005 --config-file config.yml --env HTTPSample.domain=https://${{ env.AZURE_WEBAPP_NAME }}-staging.azurewebsites.net
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: loadTestResults
          path: loadTest/results.zip
